timeouts:
  render:
    PNG_TIMEOUT: 55
    GIF_TIMEOUT: 55
    MP4_TIMEOUT: 115

layout:
  taiko:
    png:
      SPACING_PER_BPM: 0.0
    gif:
      FPS: 30.0
    mp4:
      FPS: 30.0
  mania:
    gif:
      FPS: 30
      DURATION_MS: 5000
    mp4:
      FPS: 30
